### ISSUE TITLE
Remove scheme from url

### ISSUE THREAD

**Issue by stormwild** [akrabat/slim3-skeleton#14]
To avoid mixed content issues when running slim3-skeleton from https, remove scheme from url to google fonts.

```
<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
```

in app/templates/home.twig

**Comment by akrabat** [comment]
Great idea. Fancy creating a PR?

**Comment by stormwild** [comment]
PR sent. :)
