### ISSUE TITLE
Can you show us an example cli script?

### ISSUE THREAD

**Issue by needcaffeine** [akrabat/slim3-skeleton#30]
That would be an excellent addition to the skeleton.

I can't seem to accomplish this by mocking the environment.

**Comment by akrabat** [comment]
PSR-7 isn't really designed for CLI as Request and Response are modelled on HTTP messages.

I would suggest adding [Symfony console](http://symfony.com/doc/current/cookbook/console/console_command.html) or [zfcampus/zf-console](https://github.com/zfcampus/zf-console) to your application. Your model layer should be separate from your route callables, so all your business logic is available and you can of course, use the DI container with a console component.

**Comment by needcaffeine** [comment]
Oh I never followed up with you on this. I ended up implementing Symfony console into my project. Thank you for the advice. If you think it belongs, I can add it to the skeleton.
