### ISSUE TITLE
How to use flash message?

### ISSUE THREAD

**Issue by ArneAnka** [akrabat/slim3-skeleton#32]
Hi!

How do i use the flash message?

**Comment by akrabat** [comment]
see: 
- https://github.com/akrabat/slim-bookshelf/blob/master/app/src/Bookshelf/AuthorController.php#L64
- https://github.com/akrabat/slim-bookshelf/blob/master/app/templates/bookshelf/author/books.twig#L8
- https://github.com/akrabat/slim-bookshelf/blob/master/app/src/Bookshelf/TwigExtension.php
