### ISSUE TITLE
Syntax for calling a method in a route

### ISSUE THREAD

**Issue by ghost** [akrabat/slim3-skeleton#7]
The syntax: `'App\Action\HomeAction:dispatch'` 

Where can I learn more about this? I have never encountered it before outside of a Slim3 context. Is this something unique to Slim/Pimple/FastRoute or this a feature in PHP5 that has eluded me?

I feel silly, but I would very much like to understand this seemingly simple syntactical detail.

Thank you very much for this skeleton. It is proving to be extremely helpful.

**Comment by akrabat** [comment]
This is part of Slim's [`CallableResolver`](https://github.com/slimphp/Slim/blob/3.x/Slim/CallableResolver.php#L77-L90).

**Comment by ghost** [comment]
Thank you very much, I appreciate the help.

**Comment by piotr-cz** [comment]
Just in case that somebody would be getting same error as was: `Call to undefined function App\Action\HomeAction::dispatch()`

make sure there is one semicolon, not two when defining a callable.
